.PHONY: build build-spider build-scorpion 

GO ?= go
BUILD ?= $(GO) build
BUILD_DIR ?= ./bin/

build: build-spider build-scorpion


.DEFAULT:
	@echo "Build project"
	@echo ""
	@echo "build:  Build all binaries"