FROM alpine:latest

iteramos por las urls
go {
    get a la url
    recibimos body || recibimos error
    if error {
        pausa de tiempo, aumentamos timeout
        for () {

        }
        if error {
            mandamos error, salimos
        }
    }
    visited logic
    parseamos body, obtenemos hrefs y src
    chan ok <- href, src
}
wait a que acaben
set(href)
go {
    get src
}
