ARG USER ${USER:-host}
ARG USER_PWD ${USER_PWD} 

FROM debian:bookworm

RUN apt update && \
    apt install -y lftp sshd && \
    rm -rf /var/lib/apt/lists/*
RUN usermod -d /home/${USER} -s /bin/bash ${USER} && \
    echo ${USER}:${USER_PWD} | chpasswd

USER ${USER}
WORKDIR /home/${USER}

ENTRYPOINT ["/usr/bin/sshd", "-D"]

